name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull docker image
        run:  docker pull adarsh6672/unleash-notificationserivice
      - name: delete old docker image
        run:  docker rm -f notification-service || true
      - name: run docker container
        run:  docker run -d -p 8084:8084 --name notification-service --network test_app-network adarsh6672/unleash-notificationserivice

